import express from 'express'
import makeWASocket,{DisconnectReason,fetchLatestBaileysVersion,makeCacheableSignalKeyStore,useMultiFileAuthState} from 'baileys'
import P from 'pino'
import {Boom} from '@hapi/boom'
import QRCode from 'qrcode'
import path from 'node:path'
import {fileURLToPath} from 'node:url'

const __dirname=path.dirname(fileURLToPath(import.meta.url))
const app=express(); const port=Number(process.env.PORT||3000)
const logger=P({level:process.env.LOG_LEVEL||'info'})
const chats=new Map(), messagesByChat=new Map(), lidToPn=new Map(), contactNames=new Map()
const MAX_MESSAGES_PER_CHAT=100
let connection='close',latestQr=null,connectionError=null,reconnecting=false

function archived(c){return c?.archived===true||c?.archived===1}
function canonical(jid){return lidToPn.get(jid)||jid}
function savedName(c){return contactNames.get(c?.id)||contactNames.get(canonical(c?.id))||c?.name||c?.pushName||c?.notify||c?.verifiedName||c?.id||''}
function rememberContact(c={}){const n=String(c?.name||'').trim();if(!n)return;for(const id of [c.id,c.phoneNumber,c.lid].filter(Boolean)){contactNames.set(id,n);contactNames.set(canonical(id),n)}}
function mergeIdentity(lid,pn){if(!lid||!pn||lid===pn)return;lidToPn.set(lid,pn);const lc=chats.get(lid),pc=chats.get(pn);if(lc){chats.set(pn,{...lc,...pc,id:pn});chats.delete(lid)}const lm=messagesByChat.get(lid);if(lm?.length){const all=[...(messagesByChat.get(pn)||[]),...lm];const u=new Map(all.map(m=>[m.key?.id,m]));messagesByChat.set(pn,[...u.values()].sort((a,b)=>Number(a.messageTimestamp||0)-Number(b.messageTimestamp||0)).slice(-MAX_MESSAGES_PER_CHAT));messagesByChat.delete(lid)}}
function upsertChats(items=[]){for(const c of items||[]){if(c?.id){const old=chats.get(c.id)||{};chats.set(c.id,{...old,...c})}}}
function updateChats(items=[]){for(const c of items||[]){if(c?.id){const old=chats.get(c.id)||{id:c.id};chats.set(c.id,{...old,...c})}}}
function upsertMessages(items=[]){for(const m of items||[]){const jid=m?.key?.remoteJid,id=m?.key?.id;if(!jid||!id)continue;const key=canonical(jid),list=messagesByChat.get(key)||[];if(list.some(x=>x.key?.id===id))continue;list.push(m);list.sort((a,b)=>Number(a.messageTimestamp||0)-Number(b.messageTimestamp||0));messagesByChat.set(key,list.slice(-MAX_MESSAGES_PER_CHAT))}}
function canonicalChats(){const g=new Map();for(const c of chats.values()){const id=canonical(c.id),old=g.get(id);g.set(id,old?{...old,...c,id,conversationTimestamp:Math.max(Number(old.conversationTimestamp||0),Number(c.conversationTimestamp||0))}:{...c,id})}return [...g.values()]}
function publicMessage(m){return{id:m.key?.id||null,fromMe:Boolean(m.key?.fromMe),timestamp:m.messageTimestamp||0,text:m.message?.conversation||m.message?.extendedTextMessage?.text||m.message?.imageMessage?.caption||m.message?.videoMessage?.caption||m.message?.documentMessage?.caption||null}}
function last10(c){return(messagesByChat.get(canonical(c.id))||[]).map(publicMessage).filter(m=>m.text).sort((a,b)=>Number(a.timestamp)-Number(b.timestamp)).slice(-10)}

async function startWhatsApp(){if(reconnecting)return;reconnecting=true;try{const {state,saveCreds}=await useMultiFileAuthState('.baileys_auth');const {version}=await fetchLatestBaileysVersion();const sock=makeWASocket({version,logger,auth:{creds:state.creds,keys:makeCacheableSignalKeyStore(state.keys,logger)},shouldSyncHistoryMessage:()=>true});sock.ev.on('creds.update',saveCreds);sock.ev.process(async ev=>{if(ev['connection.update']){const {connection:c,lastDisconnect,qr}=ev['connection.update'];connection=c;if(qr)latestQr=qr;if(c==='open'){latestQr=null;connectionError=null}if(c==='close'){latestQr=null;connectionError=lastDisconnect?.error?.message||null;const loggedOut=lastDisconnect?.error instanceof Boom&&lastDisconnect.error.output?.statusCode===DisconnectReason.loggedOut;if(!loggedOut)setTimeout(()=>{reconnecting=false;startWhatsApp().catch(e=>logger.error(e))},3000)}}if(ev['messaging-history.set']){const h=ev['messaging-history.set'];for(const x of h.contacts||[]){rememberContact(x);if(x.lid&&x.id?.endsWith('@s.whatsapp.net'))mergeIdentity(x.lid,x.id)}for(const x of h.lidPnMappings||[])mergeIdentity(x.lid,x.pn);if(h.isLatest||(chats.size===0&&h.syncType===0&&h.chats?.length))upsertChats(h.chats);upsertMessages(h.messages);logger.info({chats:h.chats?.length||0,messages:h.messages?.length||0,stored:chats.size},'histórico recebido')}if(!ev['messaging-history.set']&&ev['chats.upsert'])upsertChats(ev['chats.upsert']);if(ev['chats.update'])updateChats(ev['chats.update']);if(ev['chats.delete'])for(const id of ev['chats.delete'])chats.delete(id);if(ev['messages.upsert'])upsertMessages(ev['messages.upsert'].messages);if(ev['lid-mapping.update'])mergeIdentity(ev['lid-mapping.update'].lid,ev['lid-mapping.update'].pn);if(ev['contacts.upsert'])for(const c of ev['contacts.upsert']){rememberContact(c);if(c.lid&&c.id?.endsWith('@s.whatsapp.net'))mergeIdentity(c.lid,c.id)}})}finally{reconnecting=false}}

const GROQ_URL='https://api.groq.com/openai/v1/chat/completions',GROQ_MODEL='openai/gpt-oss-120b'
async function aiOrder(name,messages){const key=process.env.GROQ_API_KEY;if(!key)throw Error('GROQ_API_KEY não configurada no Render.');const context=messages.map((m,i)=>`${i+1}. ${m.fromMe?'EMPRESA':'CLIENTE'}: ${m.text}`).join('\n');const prompt=`Você é o responsável por montar pedidos do Samuel Frutas. Receba EXATAMENTE as últimas 10 mensagens de uma conversa, em ordem cronológica, misturando CLIENTE e EMPRESA.\n\nMonte o ÚLTIMO pedido tratado nessa conversa. A EMPRESA pode confirmar, corrigir, completar ou substituir quantidades informadas pelo CLIENTE. Use isso como contexto. Se houver uma correção clara da empresa, vale a correção. Ignore pedidos antigos e conversa casual. Não invente nada. Se existir qualquer item de pedido identificável, marque tem_pedido=true. Se não existir nenhum item de pedido, false.\n\nRetorne SOMENTE JSON neste formato: {"tem_pedido":true,"itens":[{"produto":"maçã","quantidade":6,"unidade":"Un"}]}\n\nNome do contato: ${name}\nMensagens:\n${context}`;const r=await fetch(GROQ_URL,{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({model:GROQ_MODEL,temperature:0,response_format:{type:'json_object'},messages:[{role:'system',content:prompt}]})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.error?.message||`Groq HTTP ${r.status}`);const raw=d?.choices?.[0]?.message?.content;if(!raw)throw Error('Groq não retornou conteúdo.');let p;try{p=JSON.parse(raw)}catch{throw Error('Groq retornou JSON inválido.')}const itens=Array.isArray(p.itens)?p.itens.map(x=>({produto:String(x?.produto||'').trim(),quantidade:Number(x?.quantidade),unidade:x?.unidade?String(x.unidade):null})).filter(x=>x.produto&&Number.isFinite(x.quantidade)&&x.quantidade>0):[];return{temPedido:Boolean(p.tem_pedido)&&itens.length>0,itens}}

app.use(express.static(path.join(__dirname,'..','public')))
app.get('/api/whatsapp/status',(_q,res)=>res.json({connection,connected:connection==='open',qrPending:Boolean(latestQr),error:connectionError}))
app.post('/api/whatsapp/connect',(_q,res)=>{if(connection==='open')return res.json({ok:true,connected:true});latestQr=null;startWhatsApp().catch(e=>logger.error(e));res.json({ok:true,connected:false})})
app.get('/api/whatsapp/qr',async(_q,res)=>latestQr?res.json({qrPending:true,dataUrl:await QRCode.toDataURL(latestQr,{margin:2,width:320})}):res.status(404).json({qrPending:false}))
app.get('/api/status',(_q,res)=>{const all=canonicalChats(),active=all.filter(c=>!archived(c));res.json({connection,totalChats:all.length,activeChats:active.length,archivedChats:all.length-active.length})})
app.get('/api/chats',(_q,res)=>res.json(canonicalChats().filter(c=>!archived(c)).sort((a,b)=>Number(b.conversationTimestamp||0)-Number(a.conversationTimestamp||0)).map(c=>({id:c.id,name:savedName(c),jid:c.id,archived:false}))))
app.get('/api/pedidos/contexto',(_q,res)=>{const active=canonicalChats().filter(c=>!archived(c));res.json({totalConversas:active.length,conversas:active.map(c=>({jid:canonical(c.id),nomeWhatsApp:savedName(c),mensagensContexto:last10(c)}))})})
app.get('/api/chats/:jid/messages',(req,res)=>{const c=canonicalChats().find(x=>canonical(x.id)===canonical(req.params.jid));if(!c)return res.status(404).json({error:'Chat não encontrado.'});if(archived(c))return res.status(403).json({error:'Chat arquivado.'});res.json({messages:last10(c)})})
app.get('/api/pedidos/interpretar',async(_q,res)=>{const active=canonicalChats().filter(c=>!archived(c)).sort((a,b)=>Number(b.conversationTimestamp||0)-Number(a.conversationTimestamp||0));const resultados=[];for(const c of active){const nome=savedName(c),mensagens=last10(c);try{const ai=await aiOrder(nome,mensagens);resultados.push({jid:canonical(c.id),nomeWhatsApp:nome,mensagensContexto:mensagens,pedido:ai.itens,pedidoStatus:ai.temPedido?'identificado':'nao_identificado',erro:null})}catch(e){resultados.push({jid:canonical(c.id),nomeWhatsApp:nome,mensagensContexto:mensagens,pedido:[],pedidoStatus:'erro',erro:e.message})}}res.json({regra:'Somente desarquivadas. Para cada conversa: últimas 10 mensagens da conversa inteira -> IA -> último pedido.',totalConversas:resultados.length,resultados})})
app.get('/health',(_q,res)=>res.json({ok:true,connection,chats:canonicalChats().length}))
app.listen(port,()=>{startWhatsApp().catch(e=>logger.error(e));console.log('Servidor do coletor rodando na porta '+port)})
